// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbjX8i_6dSuM767pMse8wO8dtyxhSuVws',
    appId: '1:794096800633:web:31eaf92c086b0337fbd5a8',
    messagingSenderId: '794096800633',
    projectId: 'golfer-7a833',
    authDomain: 'golfer-7a833.firebaseapp.com',
    storageBucket: 'golfer-7a833.firebasestorage.app',
    measurementId: 'G-N4BS584646',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP3Dx7bRKoo6eoxwoQTSezw2VJzQXs7ZI',
    appId: '1:393847689538:android:245d69329fe0c184f578db',
    messagingSenderId: '393847689538',
    projectId: 'Golfer-a4ad7',
    storageBucket: 'Golfer-a4ad7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfVf79TVxWs8InGdSruLclAYnUG2Fx4TM',
    appId: '1:393847689538:ios:06a8643bd3afce66f578db',
    messagingSenderId: '393847689538',
    projectId: 'Golfer-a4ad7',
    storageBucket: 'Golfer-a4ad7.firebasestorage.app',
    iosClientId:
        '393847689538-m7osheg4g67u0p30o2cbac1jef0eol76.apps.googleusercontent.com',
    iosBundleId: 'com.herberkom.Golfer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfVf79TVxWs8InGdSruLclAYnUG2Fx4TM',
    appId: '1:393847689538:ios:68a3b079e2adb8a3f578db',
    messagingSenderId: '393847689538',
    projectId: 'Golfer-a4ad7',
    storageBucket: 'Golfer-a4ad7.firebasestorage.app',
    iosClientId:
        '393847689538-safj0vdmen5f5p90mitja375b7h49kqc.apps.googleusercontent.com',
    iosBundleId: 'com.herberkom.Golfer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyIRbabCYaxSSqeBc6LK9xHuDvLFCLGBc',
    appId: '1:393847689538:web:e814994d7d59eb74f578db',
    messagingSenderId: '393847689538',
    projectId: 'Golfer-a4ad7',
    authDomain: 'Golfer-a4ad7.firebaseapp.com',
    storageBucket: 'Golfer-a4ad7.firebasestorage.app',
  );
}
