-- Patch existing DB for:
-- 1) One-time profile setup fields on users
-- 2) Separate subscription payment and charity donation records

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS profile_setup_completed BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS skill_level VARCHAR(24),
    ADD COLUMN IF NOT EXISTS club_affiliation VARCHAR(160);

ALTER TABLE wallets
    ADD COLUMN IF NOT EXISTS available_balance DOUBLE PRECISION DEFAULT 0.0,
    ADD COLUMN IF NOT EXISTS total_topups DOUBLE PRECISION DEFAULT 0.0,
    ADD COLUMN IF NOT EXISTS total_donated DOUBLE PRECISION DEFAULT 0.0;

UPDATE wallets
SET
    available_balance = COALESCE(available_balance, token_balance, 0.0),
    total_topups = COALESCE(total_topups, total_purchased, 0.0)
WHERE
    available_balance IS NULL
    OR total_topups IS NULL;

CREATE TABLE IF NOT EXISTS wallet_ledger (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    entry_type VARCHAR(32) NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    currency VARCHAR(8) NOT NULL DEFAULT 'USD',
    reference_type VARCHAR(48),
    reference_id VARCHAR(128),
    status VARCHAR(24) NOT NULL DEFAULT 'completed',
    metadata_json JSONB,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_wallet_ledger_user_id ON wallet_ledger(user_id);
CREATE INDEX IF NOT EXISTS ix_wallet_ledger_entry_type ON wallet_ledger(entry_type);

CREATE TABLE IF NOT EXISTS golf_subscription_payments (
    id UUID PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subscription_id UUID NOT NULL REFERENCES golf_subscriptions(id) ON DELETE CASCADE,
    plan_id VARCHAR(32) NOT NULL REFERENCES golf_subscription_plans(id),
    amount_cents BIGINT NOT NULL CHECK (amount_cents > 0),
    currency VARCHAR(8) NOT NULL DEFAULT 'USD',
    payment_provider VARCHAR(32) NOT NULL DEFAULT 'stripe',
    payment_reference VARCHAR(128),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_golf_subscription_payments_user ON golf_subscription_payments(user_id);
CREATE INDEX IF NOT EXISTS ix_golf_subscription_payments_subscription ON golf_subscription_payments(subscription_id);

CREATE TABLE IF NOT EXISTS golf_charity_donations (
    id UUID PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    charity_id UUID NOT NULL REFERENCES golf_charities(id) ON DELETE CASCADE,
    subscription_id UUID REFERENCES golf_subscriptions(id) ON DELETE SET NULL,
    amount_cents BIGINT NOT NULL CHECK (amount_cents > 0),
    currency VARCHAR(8) NOT NULL DEFAULT 'USD',
    payment_provider VARCHAR(32) NOT NULL DEFAULT 'stripe',
    payment_reference VARCHAR(128),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_golf_charity_donations_user ON golf_charity_donations(user_id);
CREATE INDEX IF NOT EXISTS ix_golf_charity_donations_charity ON golf_charity_donations(charity_id);
